### ISSUE TITLE
Improve performance of MembershipManager

### ISSUE THREAD

**Issue by claudiu-cristea** [Gizra/og#485]
In #480 the internal static cache has been replaced by using the `@cache.static` service. This, now, opens the way to double the static caching with persistent caching (database, Redis, etc).

All we need is to declare a service, such as:

```
og.membership.memory_cache:
  class: Drupal\Core\Cache\MemoryCache\MemoryCache
og.membership.cache:
  class: Drupal\Core\Cache\BackendChain
  calls:
    - [appendBackend, ['@og.membership.memory_cache']]
    - [appendBackend, ['@cache.data']]
  tags:
    # This ensures cache tag invalidation.
    - { name: cache.bin }
```
Then we just need to inject this instead of `@cache.static` and do only some renaming inside MembershipManager.

Even not used in core (but tested), `BackendChain` allows retrieving items in cascade. You can add as many backends you want. When getting an item from cache, the service will look first in the first backend (which in our case is memory). If there are items not retrieved from there, will fallback to the next defined backend and so on. All subsequent backends cache is tagged with the same tags, so invalidation will also work nice.
